### ISSUE TITLE
Tracking TODOs

### ISSUE THREAD

**Issue by owolabileg** [SoftEngResearch/emop#4]
- [x] Fix bug when calling affected-specs after the first run; the paths seem to be scrambled
- [x] Calling AJC from inside java seems much more expensive than from terminal; how to reduce cost
- [x] Produce the spec-to-classes map by processing the current messages (likely costly, but simple)
- [x] Produce the spec-to-classes map directly from inside AJC (likely faster, but we'll need to hack AJC)
- [ ] write a short design doc for how to implement the RPS variants (you may need to read portion the ICST 2019 paper again)
