### ISSUE TITLE
TODO for next submission

### ISSUE THREAD

**Issue by ayakayorihiro** [SoftEngResearch/emop#65]
- [ ] Compare current results against same versions and projects from ICSE 2019
  - [ ] Table summary in the paper for projects, versions, and variants
- [ ] Safety Experiments
  - [ ] Table summary in the paper for how many violations, and for which variants, we missed violations
- [ ] RPS + VMS
   - [ ] [4/19] Get experiment results from RPS + VMS (what do we want to show here?)
- [ ] RPP + VMS
   - [ ] Implement (get around the inheritance problem)
   - [ ] Get experiment results (what do we want to show here?)
- [ ] RPS + RPP + VMS
